# Generated by Django 3.0.2 on 2020-02-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image2_third',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='post',
            name='image_sec',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
