# Generated by Django 3.0.2 on 2020-02-01 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200201_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.CharField(default=500000, max_length=100),
            preserve_default=False,
        ),
    ]
